name: CI
on:
  push:
    branches:
    - main 
  pull_request:
    branches: 
    - main 
jobs:
  Lint:
    # 执行Lint任务
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install modules
      run: pnpm install
    - name: Lint
      run: pnpm --filter fish-design-vite run lint
  UnitTest:
    # 进行单元测试

    # 执行任务的环境
    runs-on: ubuntu-latest
    # 具体执行步骤
    steps:
    - uses: actions/checkout@v3
    - uses:  pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install modules
      run: pnpm install
    - name: Run Test
      run: pnpm --filter fish-design-vite run test:run
