
name: Publish fish-design-cli To Npm

on:
  push:
    branches:
    - publish-fish-design-cli

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish npm"

    environment: npm

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 6.0.2
    - name: Install modules
      run: pnpm install
    - name: "Publish to the npm registry"
      uses: JS-DevTools/npm-publish@v2
      with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "packages/create-fish-app-cli"
